### ISSUE TITLE
Automapper crashes if rooms are too cramped

### ISSUE THREAD

**Issue by ghost** [ggarra13/ifmapper#8]
IFMapper crashes while automapping if it tries to put a new room on the map where a room already exists. For example, in Dreamhold, trying to enter the Curving Hall, South End from the Curving Hall after you've mapped out the Curtained Room can cause this. It also happens in the Atelier whenever you try to enter a second painting.

I think ideally it should scoot part of the map over to make room and make some paths longer, or it should make the conflicting rooms smaller.

**Comment by ggarra13** [comment]
Thanks for the bug report.  Have you kept by any chance the transcript file and the IFMapper's map file before the crash?  Or can you easily recreate them?  I am busy with other projects and would not have time to play Dreamhold again or know where the rooms you mention are.

**Comment by ghost** [comment]
I still have the transcript but it can't save maps. That seems to be a separate issue. If it helps, i'm using Gargoyle on Linux Mint Xfce 22.
[Dreamhold_script.txt](https://github.com/user-attachments/files/16575930/Dreamhold_script.txt)

**Comment by ggarra13** [comment]
I've tried your transcript and did not crash on me.  I've updated git master repository and pushed a new version of the gem to rubygems.org that should fix the crash when saving the maps.

**Comment by ggarra13** [comment]
The new .gem also fixes drawing the maps with spline (curved) connections which was also crashing.

**Comment by ghost** [comment]
That fixed it. Thatks!
